// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package book

import (
	"github.com/google/wire"
	"lms/internal/book/handlers"
	"lms/internal/book/repository"
	"lms/internal/book/service"
)

// Injectors from wire.go:

// Generate dependency injection function (only defined here for Wire)
func InitializeBookHandler() handlers.BookIssuanceHandler {
	bookIssuanceRepository := repository.NewBookIssuanceRepo()
	bookIssuanceService := service.NewBookIssuanceService(bookIssuanceRepository)
	bookIssuanceHandler := handlers.NewBookIssuanceHandler(bookIssuanceService)
	return bookIssuanceHandler
}

// wire.go:

// Wire Set containing all dependencies
var BookSet = wire.NewSet(repository.NewBookIssuanceRepo, service.NewBookIssuanceService, handlers.NewBookIssuanceHandler)
